oauth:
  facebook:
    scope: "public_profile,email,user_friends"
    info_fields: "name, first_name, last_name, email"
    image_size: 'large'
meta_tags:
  og:
    type: 'website'
  fb:
    admins: '1081639010'
    image: 'http://yourdomain.jp/og.png'
  viewport: 'width=device-width,initial-scale=1,user-scalable=no'
  charset: 'utf-8'
  format:
    detection: 'telephone=no, address=no, email=no'
images:
  welcome:
    flow:
      no_illust: "illust/no-illust01.jpg"
    cover:
      active: "sample/pic/main_pict01.jpg"
      inactive: "sample/pic/main_pict02.jpg"
  noimage:
    url: 'no-image-1024x640.gif'
  noimage2:
    url: 'no-image-225x225.gif'
listing_ngevents:
  color:
    holiday: "gray"
    temporary_closed: "#FA8B9F"
    canceled: "#ccc"
# user:
#   host:
#     noname: "ホスト"
#     noname2: '名無し'
#     this: 'こちらのホスト'
#   noname: '名無し'
#   left: '退会済みユーザー'
devise:
  mailer:
    sender: 'no-reply@www.eatlocaljapan.com'
mailer:
  from:
    default: "no-reply@www.eatlocaljapan.com"
left_steps:
  listing_image: "listing_image"
  confection: "confection"
  tool: "tool"
  dress_code: "dress_code"
review:
  expiration_date: 14
listings:
  error:
    invalid_listing_id: "invalid listing id"
regulate_user:
  cancan:
    failure: "cancan faillure"
categories_for_discovery:
  - 13
  - 11
  - 26
  - 10
  - 14
  - 18
charge:
  status_classes:
    ordered: 'success'
    charging: 'primary'
    paid: 'info'
    canceling: 'danger'
    terminated: 'default'
gmo:
  link:
    params:
      credit_card:
        site_id: 'SiteID'
        member_id: 'MemberID'
        member_name: 'MemberName'
        shop_id: 'ShopID'
        member_pass_string: 'MemberPassString'
        ret_url: 'RetURL'
        cancel_url: 'CancelURL'
        datetime: 'DateTime'
        user_info: 'UserInfo'
        retry_max: 'RetryMax'
        session_timeout: 'SessionTimeout'
        enc: 'Enc'
        lang: 'Lang'
        confirm: 'Confirm'
      credit_card_response:
        shop_id: 'ShopID'
        site_id: 'SiteID'
        member_id: 'MemberID'
        datetime: 'DateTime'
        check_string: 'CheckString'
        err_code: 'ErrCode'
        err_info: 'ErrInfo'
      check_credit_card:
        shop_id: 'ShopID'
        order_id: 'OrderID'
        amount: 'Amount'
        tax: 'Tax'
        datetime: 'DateTime'
        shop_pass_string: 'ShopPassString'
        ret_url: 'RetURL'
        cancel_url: 'CancelURL'
        enc: 'Enc'
        lang: 'Lang'
        use_credit: 'UseCredit'
        job_cd: 'JobCd'
        site_id: 'SiteID'
        member_id: 'MemberID'
        member_pass_string: 'MemberPassString'
      check_credit_card_response:
        shop_id: 'ShopID'
        site_id: 'SiteID'
        job_cd: 'JobCd'
        amount: 'Amount'
        access_id: 'AccessID'
        access_pass: 'AccessPass'
        order_id: 'OrderID'
        forwarded: 'Forwarded'
        method: 'Method'
        pay_times: 'PayTimes'
        approve: 'Approve'
        card_no: 'CardNo'
        tran_id: 'TranID'
        tran_date: 'TranDate'
        check_string: 'CheckString'
        err_code: 'ErrCode'
        err_info: 'ErrInfo'
      regist_credit_card:
        site_id: 'SiteID'
        member_id: 'MemberID'
        shop_id: 'ShopID'
        order_id: 'OrderID'
        member_pass_string: 'MemberPassString'
        ret_url: 'RetURL'
        cancel_url: 'CancelURL'
        datetime: 'DateTime'
        enc: 'Enc'
        lang: 'Lang'
      regist_credit_card_response:
        site_id: 'SiteID'
        member_id: 'MemberID'
        shop_id: 'ShopID'
        order_id: 'OrderID'
        check_string: 'CheckString'
        datetime: 'DateTime'
        err_code: 'ErrCode'
        err_info: 'ErrInfo'